const email = 'hello@crow5.studio';
const works = [
  {id:'translator',group:'ai',filter:'shipped',image:'assets/v5/translator-home.png',meta:'AI 01 · 独立开发 · LEVEL B',title:'AI Translator',type:'AI 产品 / 学习工具',status:'已实现 · 待补正式发布证据',summary:'面向英语学习者的无广告 AI 翻译与生词学习工具，把一次翻译延展为可持续的学习闭环。',role:'产品设计、全栈开发、部署与验证规划',tools:'Python 3.11+ · FastAPI · Vue 3 · Redis · PostgreSQL · Docker',boundary:'已实现翻译降级、游客配额、生词本、复习与统计等能力。公开展示不包含 API Key、用户历史、数据库或部署地址；当前验证等级为 B。',next:'补齐正式 pytest、接口报告和浏览器验收记录，将验证等级提升到 A。',tags:['FastAPI','Vue 3','学习闭环'],featured:true},
  {id:'brain',group:'ai',filter:'shipped',image:'assets/v5/brain-chat.png',meta:'AI 02 · 独立开发 · LEVEL A-',title:'AI Second Brain',type:'AI 产品 / 知识库 RAG',status:'已实现 · 发布前复核',summary:'从文档解析到 SSE 对话的个人知识库系统，让私有资料真正参与日常问答。',role:'产品建模、Java 全栈开发、测试与部署',tools:'Java 17 · Spring Boot 3 · LangChain4j · Apache Tika · MySQL · Vue 3',boundary:'已覆盖多格式解析、切片、向量检索、SSE 流式对话和角色权限。用户文档、会话、模型 Key 与服务器配置不公开。',next:'恢复线上部署后补截对话与文档管理内页，复跑发布验证，生成新的发布快照。',tags:['RAG','Spring Boot','SSE'],featured:true},
  {id:'teaching',group:'ai',filter:'prototype',image:'assets/v5/teaching-home.png',meta:'AI 03 · 原型方案 · LEVEL P',title:'高中个性化教学平台 · 知衡',type:'业务原型 / 教学分析',status:'高保真原型 · 未进入开发',summary:'围绕题库、考试、掌握度、错题和练习构建三角色教学分析闭环。',role:'产品定义、信息架构、交互原型与验收设计',tools:'Vue · ECharts · RBAC · 业务流程建模',boundary:'覆盖管理员、老师和学生的演示流程，使用虚拟数据；尚未连接真实后端、数据库和文件存储。',next:'确认原型后实现后端纵向切片，并用接口、数据库和浏览器测试替换原型演示。',tags:['原型','三角色','数据闭环']},
  {id:'news',group:'ai',filter:'collab',image:'assets/v5/news-cover.png',meta:'AI 04 · 合作项目 · LEVEL C',title:'大学新闻网',type:'内容平台 / 多端体验',status:'已授权展示 · 贡献边界待补充',summary:'PC 管理端、移动 Web 与微信小程序共享后端 API 的校园新闻系统。',role:'个人负责范围待确认；此处仅记录团队项目能力',tools:'Spring Boot · Vue 3 · Vant · 微信小程序 · MySQL · MinIO',boundary:'合作项目，公开展示范围已由站点所有者确认；封面为设计版式，不使用学校实景与具体新闻内容，个人贡献边界说明待补充。',next:'补充个人贡献边界说明后，生成公开案例正文。',tags:['合作','多端','内容管理']},
  {id:'cut-01',group:'edit',filter:'sample',image:null,meta:'CUT 01 · 示例待替换',title:'一条信息的三种节奏',type:'剪辑练习 / 节奏实验',status:'素材待替换 · 预留位',summary:'用同一段信息尝试三种节奏：快速切换、留白停顿和声音先行。',role:'剪辑结构、节奏设计、字幕与声音关系',tools:'Premiere Pro · After Effects · 节奏拆解',boundary:'当前为内容结构预留位，封面等待真实片段截图替换，不使用外部占位图。',next:'替换为经授权的真实片段截图，并补充时长、版本和发布链接。',tags:['节奏','字幕','声音']},
  {id:'cut-02',group:'edit',filter:'sample',image:null,meta:'CUT 02 · 示例待替换',title:'把采访剪成一条线',type:'剪辑练习 / 叙事结构',status:'素材待替换 · 预留位',summary:'从采访素材中寻找一句主张，再用画面、停顿和环境声把它推到结尾。',role:'素材整理、叙事结构、粗剪到精剪',tools:'Premiere Pro · 音频清理 · 文字节奏',boundary:'当前为剪辑方向预留位，封面等待真实片段截图替换。',next:'建立采访剪辑模板，记录删减逻辑和最终片长。',tags:['采访','叙事','粗剪']}
];
const ideas = [{n:'01',title:'AI 的下一层不是更聪明，而是更有边界。',text:'继续研究权限、引用和可解释反馈如何成为 AI 产品体验的一部分。',status:'研究中'},{n:'02',title:'把一次剪辑交付，沉淀成可复用的节奏库。',text:'从片头、转场、字幕到声音，记录可描述、可复盘的剪辑判断。',status:'下一步'}];
const $ = (selector) => document.querySelector(selector);
const favorites = new Set(JSON.parse(localStorage.getItem('portfolio-v5-favorites') || '[]'));
let lastFocus = null;
let toastTimer;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
function badgeClass(status){const s=status.split(' · ')[0];if(s==='已实现')return 'badge ok';if(s==='示例待替换'||s==='素材待替换')return 'badge';return 'badge warm'}
function coverMarkup(work){if(work.image){return `<figure class="card-cover skeleton"><span class="card-badge"><span class="${badgeClass(work.status)}">${work.status.split(' · ')[0]}</span><span class="badge">${work.meta.split(' · ').pop()}</span></span><img src="${work.image}" alt="${work.title} 界面截图" loading="lazy" onload="this.classList.add('loaded');this.parentElement.classList.remove('skeleton')"></figure>`}return `<figure class="card-cover"><span class="card-badge"><span class="${badgeClass(work.status)}">${work.status.split(' · ')[0]}</span></span><span class="cover-placeholder"><span>COVER RESERVED</span><span>${work.status.split(' · ')[0]}</span></span></figure>`}
function cardMarkup(work,index){return `<article class="work-card reveal-card reveal-card-${index+1}" data-id="${work.id}" data-filter="${work.filter}" tabindex="0"><div class="card-body"><span class="card-index">0${index+1} / ${work.group==='ai'?'AI':'CUT'}</span><div class="card-meta"><span>${work.meta}</span></div><h3 class="card-title">${work.title}</h3><p class="card-summary">${work.summary}</p><div class="card-foot"><div class="tag-list">${work.tags.map(tag=>`<span class="tag">${tag}</span>`).join('')}</div><button class="open-card" type="button" data-open="${work.id}" aria-label="查看 ${work.title} 详情">↗</button></div></div>${coverMarkup(work)}<button class="favorite ${favorites.has(work.id)?'is-favorite':''}" type="button" data-favorite="${work.id}" aria-label="${favorites.has(work.id)?'取消收藏':'收藏'} ${work.title}">${favorites.has(work.id)?'♥':'♡'}</button></article>`}
function renderCards(group){const grid=$(`#${group}Grid`);grid.innerHTML=works.filter(work=>work.group===group).map((work,index)=>cardMarkup(work,index)).join('');bindCards(grid);}
function bindCards(grid){grid.querySelectorAll('[data-open]').forEach(button=>button.addEventListener('click',()=>openDrawer(button.dataset.open)));grid.querySelectorAll('[data-favorite]').forEach(button=>button.addEventListener('click',()=>toggleFavorite(button.dataset.favorite,button)));grid.querySelectorAll('.work-card').forEach(card=>{card.addEventListener('click',event=>{if(!event.target.closest('button'))openDrawer(card.dataset.id)});card.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('button')){event.preventDefault();openDrawer(card.dataset.id)}})});}
function applyFilter(group,value){document.querySelectorAll(`[data-filter-group="${group}"] .filter`).forEach(button=>button.classList.toggle('active',button.dataset.filter===value));const cards=[...document.querySelectorAll(`#${group}Grid .work-card`)];const visible=cards.filter(card=>value==='all'||card.dataset.filter===value);cards.forEach(card=>{card.hidden=!visible.includes(card)});$(`#${group}Empty`).hidden=visible.length>0;}
function toggleFavorite(id,button){if(favorites.has(id)){favorites.delete(id);button.textContent='♡';button.classList.remove('is-favorite');toast('已取消收藏')}else{favorites.add(id);button.textContent='♥';button.classList.add('is-favorite');toast('已收藏这件作品')}localStorage.setItem('portfolio-v5-favorites',JSON.stringify([...favorites]))}
function openDrawer(id){const work=works.find(item=>item.id===id);if(!work)return;lastFocus=document.activeElement;$('#drawerCover').innerHTML=work.image?`<img src="${work.image}" alt="${work.title} 界面截图">`:'<span class="cover-placeholder"><span>COVER RESERVED</span></span>';const fields={Meta:'meta',Title:'title',Summary:'summary',Type:'type',Status:'status',Role:'role',Tools:'tools',Boundary:'boundary',Next:'next'};Object.entries(fields).forEach(([key,field])=>{$(`#drawer${key}`).textContent=work[field]});$('#drawerFavorite').dataset.favorite=id;$('#drawerFavorite').innerHTML=`${favorites.has(id)?'♥':'♡'} <span>${favorites.has(id)?'已收藏':'收藏这件作品'}</span>`;$('#drawerFavorite').classList.toggle('is-favorite',favorites.has(id));$('#drawerBackdrop').hidden=false;document.body.classList.add('drawer-open');$('#closeDrawer').focus();}
function closeDrawer(){if($('#drawerBackdrop').hidden)return;$('#drawerBackdrop').hidden=true;document.body.classList.remove('drawer-open');if(lastFocus)lastFocus.focus();}
function copyEmail(){if(navigator.clipboard&&window.isSecureContext){navigator.clipboard.writeText(email).then(()=>toast(`邮箱已复制：${email}`)).catch(()=>toast(`请手动复制：${email}`))}else toast(`请手动复制：${email}`)}
function updateReading(){const max=document.documentElement.scrollHeight-window.innerHeight;$('#readingProgress').style.height=`${max>0?(window.scrollY/max)*100:0}%`;}
renderCards('ai');renderCards('edit');$('#ideaList').innerHTML=ideas.map(idea=>`<article class="idea"><span class="idea-number">${idea.n} / NOTE</span><div><h3>${idea.title}</h3><p>${idea.text}</p></div><span class="idea-status">${idea.status}</span></article>`).join('');
document.querySelectorAll('.hero-work[data-open]').forEach(button=>button.addEventListener('click',()=>openDrawer(button.dataset.open)));
document.querySelectorAll('.filter-bar').forEach(bar=>bar.addEventListener('click',event=>{const button=event.target.closest('.filter');if(button)applyFilter(bar.dataset.filterGroup,button.dataset.filter)}));
$('#closeDrawer').addEventListener('click',closeDrawer);$('#drawerBackdrop').addEventListener('click',event=>{if(event.target===$('#drawerBackdrop'))closeDrawer()});window.addEventListener('keydown',event=>{if(event.key==='Escape')closeDrawer()});
$('#drawerFavorite').addEventListener('click',()=>{const id=$('#drawerFavorite').dataset.favorite;const work=works.find(item=>item.id===id);const button=$('#drawerFavorite');if(favorites.has(id)){favorites.delete(id);button.innerHTML='♡ <span>收藏这件作品</span>';toast('已取消收藏')}else{favorites.add(id);button.innerHTML='♥ <span>已收藏</span>';toast('已收藏这件作品')}button.classList.toggle('is-favorite',favorites.has(id));localStorage.setItem('portfolio-v5-favorites',JSON.stringify([...favorites]));const cardButton=document.querySelector(`[data-favorite="${work.id}"]`);if(cardButton){cardButton.textContent=favorites.has(id)?'♥':'♡';cardButton.classList.toggle('is-favorite',favorites.has(id))}});
$('#copyEmail').addEventListener('click',copyEmail);const menu=$('#menuToggle');menu.addEventListener('click',()=>{const open=$('#siteNav').classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'关闭导航菜单':'打开导航菜单')});document.querySelectorAll('#siteNav a').forEach(link=>link.addEventListener('click',()=>{$('#siteNav').classList.remove('open');menu.setAttribute('aria-expanded','false')}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});const sections=[...document.querySelectorAll('.story-section')];sections.forEach(section=>revealObserver.observe(section));
const navLinks=[...document.querySelectorAll('.site-nav a')];
function updateNav(){const marker=window.scrollY+window.innerHeight*.3;let current=navLinks[0];sections.forEach(section=>{if(section.getBoundingClientRect().top+window.scrollY<=marker)current=navLinks.find(link=>link.dataset.section===section.dataset.section)||current});navLinks.forEach(link=>link.classList.toggle('active',link===current))}
window.addEventListener('scroll',updateNav,{passive:true});window.addEventListener('resize',updateNav);updateNav();
const cardObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');cardObserver.unobserve(entry.target)}}),{threshold:.18});document.querySelectorAll('.reveal-card').forEach(card=>cardObserver.observe(card));
window.addEventListener('scroll',updateReading,{passive:true});window.addEventListener('resize',updateReading);updateReading();
