const email = 'hello@crow5.studio';
const works = [
  {id:'translator',group:'ai',filter:'shipped',cover:'cover-translator',meta:'AI 01 · 独立开发 · LEVEL B',title:'LexiFlow',type:'AI 产品 / 学习工具',status:'已实现 · 待补正式发布证据',summary:'面向英语学习者的无广告 AI 翻译与生词学习工具，把一次翻译延展为可持续的学习闭环。',role:'产品设计、全栈开发、部署与验证规划',tools:'Python 3.11+ · FastAPI · Vue 3 · Redis · PostgreSQL · Docker',boundary:'已实现翻译降级、游客配额、生词本、复习与统计等能力。公开展示不包含 API Key、用户历史、数据库或部署地址；当前验证等级为 B。',next:'补齐正式 pytest、接口报告和浏览器验收记录，将验证等级提升到 A。',tags:['FastAPI','Vue 3','学习闭环'],featured:true},
  {id:'brain',group:'ai',filter:'shipped',cover:'cover-brain',meta:'AI 02 · 独立开发 · LEVEL A-',title:'AI Second Brain',type:'AI 产品 / 知识库 RAG',status:'已实现 · 发布前复核',summary:'从文档解析到 SSE 对话的个人知识库系统，让私有资料真正参与日常问答。',role:'产品建模、Java 全栈开发、测试与部署',tools:'Java 17 · Spring Boot 3 · LangChain4j · Apache Tika · MySQL · Vue 3',boundary:'已覆盖多格式解析、切片、向量检索、SSE 流式对话和角色权限。用户文档、会话、模型 Key 与服务器配置不公开。',next:'复跑单元测试、构建与链接验证，生成新的发布快照。',tags:['RAG','Spring Boot','SSE']},
  {id:'teaching',group:'ai',filter:'prototype',cover:'cover-teaching',meta:'AI 03 · 原型方案 · LEVEL P',title:'高中个性化教学平台',type:'业务原型 / 教学分析',status:'高保真原型 · 未进入开发',summary:'围绕题库、考试、掌握度、错题和练习构建三角色教学分析闭环。',role:'产品定义、信息架构、交互原型与验收设计',tools:'Vue · ECharts · RBAC · 业务流程建模',boundary:'覆盖管理员、老师和学生的演示流程，使用虚拟数据；尚未连接真实后端、数据库和文件存储。',next:'确认原型后实现后端纵向切片，并用接口、数据库和浏览器测试替换原型演示。',tags:['原型','三角色','数据闭环']},
  {id:'news',group:'ai',filter:'collab',cover:'cover-news',meta:'AI 04 · 合作项目 · LEVEL C',title:'大学新闻网',type:'内容平台 / 多端体验',status:'受限展示 · 等待授权确认',summary:'PC 管理端、移动 Web 与微信小程序共享后端 API 的校园新闻系统。',role:'个人负责范围待确认；此处仅记录团队项目能力',tools:'Spring Boot · Vue 3 · Vant · 微信小程序 · MySQL · MinIO',boundary:'合作项目。必须确认个人贡献、学校数据授权和视觉素材权属，不将团队成果表述为独立完成。',next:'建立贡献边界说明和授权审查包后，生成公开案例正文。',tags:['合作','多端','内容管理']},
  {id:'cut-01',group:'edit',filter:'sample',cover:'cover-cut',meta:'CUT 01 · 示例待替换',title:'一条信息的三种节奏',type:'剪辑练习 / 节奏实验',status:'示例待替换 · CSS 封面',summary:'用同一段信息尝试三种节奏：快速切换、留白停顿和声音先行。',role:'剪辑结构、节奏设计、字幕与声音关系',tools:'Premiere Pro · After Effects · 节奏拆解',boundary:'当前为内容结构示例，不代表真实发布作品；封面为 CSS 视觉构成，无外部图片资源。',next:'替换为经授权的真实片段，并补充时长、版本和发布链接。',tags:['节奏','字幕','声音']},
  {id:'cut-02',group:'edit',filter:'sample',cover:'cover-story',meta:'CUT 02 · 示例待替换',title:'把采访剪成一条线',type:'剪辑练习 / 叙事结构',status:'示例待替换 · CSS 封面',summary:'从采访素材中寻找一句主张，再用画面、停顿和环境声把它推到结尾。',role:'素材整理、叙事结构、粗剪到精剪',tools:'Premiere Pro · 音频清理 · 文字节奏',boundary:'当前为剪辑方向样例，不包含外部素材和占位图；真实内容待替换。',next:'建立采访剪辑模板，记录删减逻辑和最终片长。',tags:['采访','叙事','粗剪']}
];
const ideas = [{n:'01',title:'AI 的下一层不是更聪明，而是更有边界。',text:'继续研究权限、引用和可解释反馈如何成为 AI 产品体验的一部分。',status:'研究中'},{n:'02',title:'把一次剪辑交付，沉淀成可复用的节奏库。',text:'从片头、转场、字幕到声音，记录可描述、可复盘的剪辑判断。',status:'下一步'}];
const $ = (s) => document.querySelector(s); const toast = (message) => { const el=$('#toast'); el.textContent=message; el.hidden=false; clearTimeout(window.toastTimer); window.toastTimer=setTimeout(()=>el.hidden=true,2200); };
const favorites = new Set(JSON.parse(localStorage.getItem('portfolio-v3-favorites') || '[]'));
function renderCards(group, target, empty){const grid=$(target); const list=works.filter(w=>w.group===group); grid.innerHTML=list.map(w=>`<article class="work-card ${w.featured?'featured':''}" data-filter="${w.filter}" data-id="${w.id}" tabindex="0"><div class="card-cover ${w.cover}"><span class="cover-label">${w.group==='ai'?'AI / ARCHIVE':'EDIT / STUDY'}</span><span class="cover-lines"></span></div><div class="card-meta"><span>${w.meta}</span><span>${w.status.split(' · ')[0]}</span></div><h3 class="card-title">${w.title}</h3><p class="card-summary">${w.summary}</p><div class="card-foot"><div class="tag-list">${w.tags.map(t=>`<span class="tag">${t}</span>`).join('')}</div><button class="open-card" data-open="${w.id}" type="button" aria-label="查看 ${w.title} 详情">↗</button></div><button class="favorite ${favorites.has(w.id)?'is-favorite':''}" data-favorite="${w.id}" type="button" aria-label="${favorites.has(w.id)?'取消收藏':'收藏'} ${w.title}">${favorites.has(w.id)?'♥':'♡'}</button></article>`).join(''); empty.hidden=list.length>0; grid.querySelectorAll('[data-open]').forEach(b=>b.addEventListener('click',()=>openDrawer(b.dataset.open))); grid.querySelectorAll('.work-card').forEach(c=>c.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();openDrawer(c.dataset.id)}})); grid.querySelectorAll('[data-favorite]').forEach(b=>b.addEventListener('click',()=>toggleFavorite(b.dataset.favorite,b)));}
function applyFilter(group, value){document.querySelectorAll(`[data-filter-group="${group}"] .filter`).forEach(b=>b.classList.toggle('active',b.dataset.filter===value));document.querySelectorAll(`#${group==='ai'?'aiGrid':'editGrid'} .work-card`).forEach(c=>c.hidden=value!=='all'&&c.dataset.filter!==value);$(group==='ai'?'#aiEmpty':'#editEmpty').hidden=[...document.querySelectorAll(`#${group==='ai'?'aiGrid':'editGrid'} .work-card`)].some(c=>!c.hidden);}
function toggleFavorite(id,button){if(favorites.has(id)){favorites.delete(id);button.textContent='♡';button.classList.remove('is-favorite');toast('已取消收藏')}else{favorites.add(id);button.textContent='♥';button.classList.add('is-favorite');toast('已收藏这件作品')}localStorage.setItem('portfolio-v3-favorites',JSON.stringify([...favorites]));}
let lastFocus=null; function openDrawer(id){const w=works.find(x=>x.id===id);lastFocus=document.activeElement;$('#drawerCover').className=`drawer-cover ${w.cover}`;['Meta','Title','Summary','Type','Status','Role','Tools','Boundary','Next'].forEach(key=>{const map={Meta:'meta',Title:'title',Summary:'summary',Type:'type',Status:'status',Role:'role',Tools:'tools',Boundary:'boundary',Next:'next'}; $(`#drawer${key}`).textContent=w[map[key]]});$('#drawerFavorite').innerHTML=`${favorites.has(id)?'♥':'♡'} <span>${favorites.has(id)?'已收藏':'收藏这件作品'}</span>`;$('#drawerFavorite').dataset.favorite=id;$('#drawerBackdrop').hidden=false;document.body.style.overflow='hidden';$('#closeDrawer').focus();}
function closeDrawer(){if($('#drawerBackdrop').hidden)return;$('#drawerBackdrop').hidden=true;document.body.style.overflow='';if(lastFocus)lastFocus.focus();}
renderCards('ai','#aiGrid','#aiEmpty');renderCards('edit','#editGrid','#editEmpty');$('#ideaList').innerHTML=ideas.map(i=>`<article class="idea"><span class="idea-number">${i.n} / NOTE</span><div><h3>${i.title}</h3><p>${i.text}</p></div><span class="idea-status">${i.status}</span></article>`).join('');
document.querySelectorAll('.filter-bar').forEach(bar=>bar.addEventListener('click',e=>{const b=e.target.closest('.filter');if(b)applyFilter(bar.dataset.filterGroup,b.dataset.filter)}));$('#closeDrawer').addEventListener('click',closeDrawer);$('#drawerBackdrop').addEventListener('click',e=>{if(e.target===$('#drawerBackdrop'))closeDrawer()});window.addEventListener('keydown',e=>{if(e.key==='Escape')closeDrawer()});$('#drawerFavorite').addEventListener('click',()=>{const id=$('#drawerFavorite').dataset.favorite;const fake={textContent:'',classList:{add(){},remove(){}}};toggleFavorite(id,fake);$('#drawerFavorite').innerHTML=`${favorites.has(id)?'♥':'♡'} <span>${favorites.has(id)?'已收藏':'收藏这件作品'}</span>`});
async function copyEmail(){try{await navigator.clipboard.writeText(email);toast(`邮箱已复制：${email}`)}catch{toast(`请手动复制：${email}`)}}$('#copyEmail').addEventListener('click',copyEmail);$('#copyEmailAbout').addEventListener('click',copyEmail);const menu=$('#menuToggle');menu.addEventListener('click',()=>{const open=$('#siteNav').classList.toggle('open');menu.setAttribute('aria-expanded',open);menu.setAttribute('aria-label',open?'关闭导航菜单':'打开导航菜单')});document.querySelectorAll('#siteNav a').forEach(a=>a.addEventListener('click',()=>{$('#siteNav').classList.remove('open');menu.setAttribute('aria-expanded','false')}));
